"""added spouse column

Revision ID: a218744ab1f4
Revises: e12e9d39053f
Create Date: 2020-01-04 16:12:13.413563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a218744ab1f4'
down_revision = 'e12e9d39053f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('spouse', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'spouse')
    # ### end Alembic commands ###
